language: go

go:
  - 1.14

before_script:
  - psql -c 'create database gossha_test;' -U postgres
  - mysql -e 'create database gossha_test;'


script:
  - make golint
  - make check

services:
  - postgresql
  - mysql
